require "bundler/gem_tasks"
require "rake/testtask"
require 'yard'
task :default => :run

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList['test/test.rb']
end

task :run => :test do
	ruby "2.rb"
end

YARD::Rake::YardocTask.new(:doc) do |t|
	t.files = ['*rb']
end
